#!/bin/sh
# Start/Stop the SUSI.AI main program

# this wrapper is installed as follows:
# user mode
#   .../SUSI.AI/bin/
#   .../SUSI.AI/pythonmods/
# system mode
#   prefix/bin/
#   prefix/lib/SUSI.AI/pythonmods


do_start() {
    DIR="$(dirname "$(readlink -f "$0")")"
    PMA="$(readlink -m "$DIR/../pythonmods")"
    PMB="$(readlink -m "$DIR/../lib/SUSI.AI/pythonmods")"
    if [ -d "$PMA" ] && [ -r "$PMA/susi_linux" ] ; then
        PYTHONPATH="$PMA":$PYTHONPATH
        export PYTHONPATH
    elif [ -d "$PMB" ] && [ -r "$PMB/susi_linux" ] ; then
        PYTHONPATH="$PMB":$PYTHONPATH
        export PYTHONPATH
    else
        echo "Cannot find SUSI.AI pythonmods, trying without it" >&2
    fi
    exec python3 -m susi_linux -v --short-log
}

do_stop() {
    pkill -f susi_linux
}

case "$1" in
    start)
        do_start ;;
    stop)  
        do_stop  ;;
    restart)
        do_stop ; sleep 1 ; do_start ;;
    *) 
        echo "Usage: susi-linux {start|stop|restart}" >&2
        exit 1
        ;;
esac


